import { readable, writable } from 'svelte/store'

export const SessionStore = writable({
  extension_pubkey: null,
  extension_relays: null,
  kind10002_relay_event: null,
  kind10002_relays: null,
  target_deletion_event_id: null,
  target_deletion_event: null,
  signed_deletion_event: null
});

export const RelayStore = writable([
  {"relay_url": "wss://nostr.mutinywallet.com", "checked": true, "state": null},
  {"relay_url": "wss://relay.damus.io", "checked": true, "state": null},
  {"relay_url": "wss://nos.lol", "checked": true, "state": null},
  {"relay_url": "wss://relay.snort.social", "checked": true, "state": null},
  {"relay_url": "wss://brb.io", "checked": true, "state": null}
]);

export const TopRelayStore = [
  "wss://nos.lol",
  "wss://relay.current.fyi",
  "wss://relay.wellorder.net",
  "wss://nostr-pub.wellorder.net",
  "wss://e.nos.lol",
  "wss://no.str.cr",
  "wss://nostr.oxtr.dev",
  "wss://nostr.mom",
  "wss://offchain.pub",
  "wss://relay.nostrview.com",
  "wss://nostr.wine",
  "wss://relay.snort.social",
  "wss://relay.nostr.bg",
  "wss://nostr.einundzwanzig.space",
  "wss://nostr.relayer.se",
  "wss://relay.austrich.net",
  "wss://nostr.cercatrova.me",
  "wss://nostr.vulpem.com",
  "wss://nostr.1729.cloud",
  "wss://eden.nostr.land",
  "wss://nostr-relay.freedomnode.com",
  "wss://nostr.klabo.blog",
  "wss://sg.qemura.xyz",
  "wss://nostr-relay.xbytez.io",
  "wss://relay.nostr.wirednet.jp",
  "wss://nostr.swiss-enigma.ch",
  "wss://relay.t5y.ca",
  "wss://nostr.test.aesyc.io",
  "wss://nostr.thomascdnns.com",
  "wss://relay.nostr.scot",
  "wss://relay.zeh.app",
  "wss://nostr.supremestack.xyz",
  "wss://relay.nostr.net.in",
  "wss://eosla.com",
  "wss://nostr.data.haus",
  "wss://nostr.mouton.dev",
  "wss://relay.nostr.vet",
  "wss://nostr.massmux.com",
  "wss://nostr-relay.alekberg.net",
  "wss://nostrical.com",
  "wss://relay.nostrgraph.net",
  "wss://relay.sendstr.com",
  "wss://nostr.zkid.social",
  "wss://relay.nostr.ro",
  "wss://nostr.bostonbtc.com",
  "wss://relay.cryptocculture.com",
  "wss://nostr.walletofsatoshi.com",
  "wss://nostr.mwmdev.com",
  "wss://nostr.bongbong.com",
  "wss://nostr.cro.social",
  "wss://relay.taxi",
  "wss://relay.dwadziesciajeden.pl",
  "wss://knostr.neutrine.com",
  "wss://relay.kronkltd.net",
  "wss://nostr.radixrat.com",
  "wss://nostr3.actn.io",
  "wss://relay.orangepill.dev",
  "wss://relay.ryzizub.com",
  "wss://relay.honk.pw",
  "wss://puravida.nostr.land",
  "wss://nostr1.tunnelsats.com",
  "wss://nostr.hackerman.pro",
  "wss://nostr.sidnlabs.nl",
  "wss://zur.nostr.sx",
  "wss://nostr.f44.dev",
  "wss://nostr-verified.wellorder.net",
  "wss://nostr-relay.digitalmob.ro",
  "wss://nostr-verif.slothy.win",
  "wss://relay.1bps.io",
  "wss://nostr.easydns.ca",
  "wss://relay.nostriches.org",
  "wss://relay.nostr.africa",
  "wss://nostr-relay.nokotaro.com",
  "wss://nostr-bg01.ciph.rs",
  "wss://blg.nostr.sx",
  "wss://nostr.shmueli.org",
  "wss://no.str.watch",
  "wss://nostr.sg",
  "wss://nostr2.actn.io",
  "wss://relay.nostrzoo.com",
  "wss://nostr.pleb.network",
  "wss://nostr.mustardnodes.com",
  "wss://nostr.nodeofsven.com",
  "wss://relay.nostr.vision",
  "wss://nostr.zoomout.chat",
  "wss://spore.ws",
  "wss://nostrich.friendship.tw",
  "wss://nostr.bitcoin.sex",
  "wss://cloudnull.land",
  "wss://nostr.beta3.dev",
  "wss://btc.klendazu.com",
  "wss://nostream-production-5895.up.railway.app",
  "wss://nostr.ethtozero.fr",
  "wss://nostr.kollider.xyz",
  "wss://nostr.milou.lol",
  "wss://nostr.sandwich.farm",
  "wss://nostr.blocs.fr",
  "wss://nostr.adpo.co",
  "wss://nostr.8e23.net",
  "wss://nostr.developer.li",
  "wss://nostr.zxcvbn.space",
  "wss://relay.nostr-latam.link",
  "wss://relay.n057r.club",
  "wss://nostr.whoop.ph",
  "wss://paid.spore.ws",
  "wss://relay.nostrati.com",
  "wss://relay.nostr.au",
  "wss://nostr-01.dorafactory.org",
  "wss://global-relay.cesc.trade",
  "wss://relay.nostr.info",
  "wss:///no.str.cr",
  "wss://nostr.decentony.com",
  "wss://public.nostr.swissrouting.com",
  "wss://nostr.jimc.me",
  "wss://nostr.btcmp.com",
  "wss://nostr.actn.io",
  "wss://nostr.noones.com",
  "wss://nostr.drss.io",
  "wss://relay.damus.io",
  "wss://nostr.lnprivate.network",
  "wss://nostr.fmt.wiz.biz",
  "wss://nostr.thesimplekid.com",
  "wss://relay.nostr.com.au",
  "wss://bitcoinmaximalists.online",
  "wss://nostr.coinos.io",
  "wss://nostr.fediverse.jp",
  "wss://rsslay.nostr.moe",
  "wss://private.red.gb.net",
  "wss://nostr.bitcoinplebs.de",
  "wss://nostr.gromeul.eu",
  "wss://paid.no.str.cr",
  "wss://at.nostrworks.com",
  "wss://relay.stoner.com",
  "wss://relay.nostr.moe",
  "wss://nostr.ownscale.org",
  "wss://relay.nostr.nu",
  "wss://nostr.blockchaincaffe.it",
  "wss://merrcurr.up.railway.app",
  "wss://relay.nvote.co",
  "wss://nostr.corebreach.com",
  "wss://nostr.hugo.md",
  "wss://nostr.1f52b.xyz",
  "wss://nostr-relay.bitcoin.ninja",
  "wss://nostr.terminus.money",
  "wss://nostr.sebastix.dev",
  "wss://nostr.coollamer.com",
  "wss://relay.nostr.jhot.me",
  "wss://private-nostr.v0l.io",
  "wss://nostr-pub.semisol.dev",
  "wss://relay.beta.fogtype.com"
];
